# Generated by Django 3.2.7 on 2022-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tekst', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='hover')),
                ('slug', models.SlugField(unique=True)),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
    ]
